 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/performers", type: :request do
  # Performer. As you add validations to Performer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Performer.create! valid_attributes
      get performers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      performer = Performer.create! valid_attributes
      get performer_url(performer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_performer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      performer = Performer.create! valid_attributes
      get edit_performer_url(performer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Performer" do
        expect {
          post performers_url, params: { performer: valid_attributes }
        }.to change(Performer, :count).by(1)
      end

      it "redirects to the created performer" do
        post performers_url, params: { performer: valid_attributes }
        expect(response).to redirect_to(performer_url(Performer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Performer" do
        expect {
          post performers_url, params: { performer: invalid_attributes }
        }.to change(Performer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post performers_url, params: { performer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested performer" do
        performer = Performer.create! valid_attributes
        patch performer_url(performer), params: { performer: new_attributes }
        performer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the performer" do
        performer = Performer.create! valid_attributes
        patch performer_url(performer), params: { performer: new_attributes }
        performer.reload
        expect(response).to redirect_to(performer_url(performer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        performer = Performer.create! valid_attributes
        patch performer_url(performer), params: { performer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested performer" do
      performer = Performer.create! valid_attributes
      expect {
        delete performer_url(performer)
      }.to change(Performer, :count).by(-1)
    end

    it "redirects to the performers list" do
      performer = Performer.create! valid_attributes
      delete performer_url(performer)
      expect(response).to redirect_to(performers_url)
    end
  end
end
