default: &default
  adapter: postgresql

development:
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_TEST'] %>

staging:
  <<: *default

production:
  <<: *default
